# Generated by Django 3.1.1 on 2020-09-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwordlist',
            old_name='instruction',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='userwordlist',
            old_name='pageTitle',
            new_name='word',
        ),
    ]
