# Generated by Django 3.1.1 on 2021-01-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userList', '0006_auto_20210103_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordlist',
            name='definition',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='userwordlist',
            name='word',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
    ]
