# Generated by Django 3.1.1 on 2021-01-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userList', '0011_auto_20210103_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordlist',
            name='definition',
            field=models.CharField(default='', max_length=240),
        ),
    ]
